services:
  ghost:
    image: ghost:latest
    ports:
      - "2368:2368"
    volumes:
      - ghost_content:/var/lib/ghost/content
      - ${GHOST_THEMES_DIR:-./content/themes}:/var/lib/ghost/content/themes:ro
    environment:
      NODE_ENV: development
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: ghost
      database__connection__database: ghost
      url: http://localhost:2368
      paths__contentPath: /var/lib/ghost/content
      server__development__watch: true
      caching__enabled: false
      caching__frontend__maxAge: 0
      caching__theme__maxAge: 0
      logging__level: debug
      i18n__caching: false
    user: "node"
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ghostroot
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghost
      MYSQL_DATABASE: ghost
    volumes:
      - ghost_db:/var/lib/mysql
    restart: always

volumes:
  ghost_content:
  ghost_db:
